const statesAndCapitals = {
    'USA': [
        { state: 'California', capital: 'Sacramento' },
        { state: 'Texas', capital: 'Austin' },
        { state: 'Florida', capital: 'Tallahassee' },
        { state: 'New York', capital: 'Albany' },
        { state: 'Illinois', capital: 'Springfield' },
        { state: 'Pennsylvania', capital: 'Harrisburg' },
        { state: 'Ohio', capital: 'Columbus' },
        { state: 'Georgia', capital: 'Atlanta' },
        { state: 'North Carolina', capital: 'Raleigh' },
        { state: 'Michigan', capital: 'Lansing' }
    ],
    'CANADA': [
        { state: 'Alberta', capital: 'Edmonton' },
        { state: 'British Columbia', capital: 'Victoria' },
        { state: 'Manitoba', capital: 'Winnipeg' },
        { state: 'New Brunswick', capital: 'Fredericton' },
        { state: 'Newfoundland and Labrador', capital: 'St. John\'s' },
        { state: 'Nova Scotia', capital: 'Halifax' },
        { state: 'Ontario', capital: 'Toronto' },
        { state: 'Prince Edward Island', capital: 'Charlottetown' },
        { state: 'Quebec', capital: 'Quebec City' },
        { state: 'Saskatchewan', capital: 'Regina' }
    ],
    'AUSTRALIA': [
        { state: 'New South Wales', capital: 'Sydney' },
        { state: 'Victoria', capital: 'Melbourne' },
        { state: 'Queensland', capital: 'Brisbane' },
        { state: 'South Australia', capital: 'Adelaide' },
        { state: 'Western Australia', capital: 'Perth' },
        { state: 'Tasmania', capital: 'Hobart' },
        { state: 'Northern Territory', capital: 'Darwin' },
        { state: 'Australian Capital Territory', capital: 'Canberra' },
    ],
    'INDIA': [
        { state: 'Andhra Pradesh', capital: 'Amaravati' },
        { state: 'Assam', capital: 'Dispur' },
        { state: 'Bihar', capital: 'Patna' },
        { state: 'Chhattisgarh', capital: 'Raipur' },
        { state: 'Goa', capital: 'Panaji' },
        { state: 'Gujarat', capital: 'Gandhinagar' },
        { state: 'Haryana', capital: 'Chandigarh' },
        { state: 'Himachal Pradesh', capital: 'Shimla' },
        { state: 'Jharkhand', capital: 'Ranchi' },
        { state: 'Karnataka', capital: 'Bengaluru' },
        { state: 'Kerala', capital: 'Thiruvananthapuram' },
        { state: 'Madhya Pradesh', capital: 'Bhopal' },
        { state: 'Maharashtra', capital: 'Mumbai' },
        { state: 'Manipur', capital: 'Imphal' },
        { state: 'Meghalaya', capital: 'Shillong' },
        { state: 'Mizoram', capital: 'Aizawl' },
        { state: 'Nagaland', capital: 'Kohima' },
        { state: 'Odisha', capital: 'Bhubaneswar' },
        { state: 'Punjab', capital: 'Chandigarh' },
        { state: 'Rajasthan', capital: 'Jaipur' },
        { state: 'Sikkim', capital: 'Gangtok' },
        { state: 'Tamil Nadu', capital: 'Chennai' },
        { state: 'Telangana', capital: 'Hyderabad' },
        { state: 'Tripura', capital: 'Agartala' },
        { state: 'Uttar Pradesh', capital: 'Lucknow' },
        { state: 'Uttarakhand', capital: 'Dehradun' },
        { state: 'West Bengal', capital: 'Kolkata' },
    ],
    'GERMANY': [
        { state: 'Baden-Württemberg', capital: 'Stuttgart' },
        { state: 'Bavaria', capital: 'Munich' },
        { state: 'Berlin', capital: 'Berlin' },
        { state: 'Brandenburg', capital: 'Potsdam' },
        { state: 'Bremen', capital: 'Bremen' },
        { state: 'Hamburg', capital: 'Hamburg' },
        { state: 'Hesse', capital: 'Wiesbaden' },
        { state: 'Lower Saxony', capital: 'Hanover' },
        { state: 'Mecklenburg-Vorpommern', capital: 'Schwerin' },
        { state: 'North Rhine-Westphalia', capital: 'Düsseldorf' },
        { state: 'Rhineland-Palatinate', capital: 'Mainz' },
        { state: 'Saarland', capital: 'Saarbrücken' },
        { state: 'Saxony', capital: 'Dresden' },
        { state: 'Saxony-Anhalt', capital: 'Magdeburg' },
        { state: 'Schleswig-Holstein', capital: 'Kiel' },
        { state: 'Thuringia', capital: 'Erfurt' },
    ],
    'BRAZIL': [
        { state: 'Acre', capital: 'Rio Branco' },
        { state: 'Alagoas', capital: 'Maceió' },
        { state: 'Amapá', capital: 'Macapá' },
        { state: 'Amazonas', capital: 'Manaus' },
        { state: 'Bahia', capital: 'Salvador' },
        { state: 'Ceará', capital: 'Fortaleza' },
        { state: 'Distrito Federal', capital: 'Brasília' },
        { state: 'Espírito Santo', capital: 'Vitória' },
        { state: 'Goiás', capital: 'Goiânia' },
        { state: 'Maranhão', capital: 'São Luís' },
        { state: 'Mato Grosso', capital: 'Cuiabá' },
        { state: 'Mato Grosso do Sul', capital: 'Campo Grande' },
        { state: 'Minas Gerais', capital: 'Belo Horizonte' },
        { state: 'Pará', capital: 'Belém' },
        { state: 'Paraíba', capital: 'João Pessoa' },
        { state: 'Paraná', capital: 'Curitiba' },
        { state: 'Pernambuco', capital: 'Recife' },
        { state: 'Piauí', capital: 'Teresina' },
        { state: 'Rio de Janeiro', capital: 'Rio de Janeiro' },
        { state: 'Rio Grande do Norte', capital: 'Natal' },
        { state: 'Rio Grande do Sul', capital: 'Porto Alegre' },
        { state: 'Rondônia', capital: 'Porto Velho' },
        { state: 'Roraima', capital: 'Boa Vista' },
        { state: 'Santa Catarina', capital: 'Florianópolis' },
        { state: 'São Paulo', capital: 'São Paulo' },
        { state: 'Sergipe', capital: 'Aracaju' },
        { state: 'Tocantins', capital: 'Palmas' },
    ],
};


export default statesAndCapitals;
